name: uptaxi_all_cross_platform
description: UpTaxi app for Client

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:

    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:

  flutter_test:
    sdk: flutter

  shared_preferences: ^0.5.1+2

  build_runner: ^0.9.0
  flutter_asset_generator: ^0.1.2
  http: ^0.12.0
  flutter_bloc: ^0.9.1
  equatable: ^0.1.0

flutter:
  assets:
    - assets/

  uses-material-design: true
